### ISSUE TITLE
[API 명세서] 공통/회원 관리/회원가입

### ISSUE THREAD

**Issue by JYOH3246** [JYOH3246/BackOffice#2]
현재 명세서 request는
{
   "email":"String",
   "password":"String",
   "nickName":"String",
   "role":"String"
}
아래와 같이 구성되어 있습니다.
그런데 기획상으로는 비밀번호 재입력 / 핸드폰 번호도 들어가 있습니다.
해당 내용을 request에 포함시키는 것이 좋지 않을까요?

**Comment by JYOH3246** [comment]
예를 들면
{
"email":"String",
"password":"String",
"reenter": "String"
"nickName":"String",
"role":"String"
"phonenumber" : "String"
}

**Comment by lovelyunsh** [comment]
reenter의 경우는 client측에서만 검사를 해도 충분하지 않을까 싶습니다.

phonenumber는 camel case를 적용해서 phoneNumber로 해서 수정 하면 될 것 같습니다!

**Comment by JYOH3246** [comment]
회원 가입 시 보여주는 response가 없어 우선은 email 형태로 구현해두었습니다.
추후 수정할 부분이 있다면 논의해보면 될 듯합니다.
