### ISSUE TITLE
[API 명세서] 가게 삭제 

### ISSUE THREAD

**Issue by YJ9352** [JYOH3246/BackOffice#21]
현재 api 명세서에 가게 생성 /조회 /수정 까지는 있는데 삭제가 없었습니다.
하지만 실제 배달앱에서는 가게가 폐업하는 경우가 있는데 
그 상태를 표시하기 위해 삭제 대신 메뉴에서처럼 enum으로 폐업 상태로 처리하는게 좋을 것 같습니다.

**Comment by lovelyunsh** [comment]
좋습니다. 가게에도 status를 표시 할 수 있게 해서 soft delete를 해야겠군요!
