### ISSUE TITLE
[bug] SQL 예약어로 인한 에러 발생

### ISSUE THREAD

**Issue by lovelyunsh** [JYOH3246/BackOffice#24]
저희의 주문 테이블 명이 예약어 중 하나인 order라서 (order by등에 사용)
ddl 생성 시 sql 에러가 발생하였습니다.

검색으로 해결 방법을 찾아 공유 드립니다.

```
//수정 전 오류 발생
@Column(name = "match")
@Table(name = "order")

//이스케이프 시퀀스
@Column(name = "\"match\"")
@Table(name = "\"order\"")

//백틱
@Column(name = "`match`")
@Table(name = "`order`")
```

저희 코드에서는
백틱을 이용해서 해결 하였습니다.
```
@Entity
@Table(name = "`order`")
```

**Comment by JYOH3246** [comment]
user의 경우에도 그런 문제가 있어서, 저는 테이블 이름을 app_user라고 정해놓았었습니다.
이런 방법도 있었네요. 감사합니다 :)
