### ISSUE TITLE
[API 명세서] 공통/회원 관리/로그인

### ISSUE THREAD

**Issue by JYOH3246** [JYOH3246/BackOffice#3]
이전 팀프로젝트때 Request에 Role을 포함시켜 구현한 적 있었는데 그때 받았던 피드백 중 하나가 "Role을 굳이 입력받을 필요가 없다." 였습니다. 로그인의 편의성 측면에서 Role을 로그인할때 굳이 받을 필요가 있을까라는 생각이 듭니다.

**Comment by lovelyunsh** [comment]
좋은 의견 인 것 같습니다. role에 따라 로그인을 분리할 필요가 굳이 없을 것 같네요. role 없이 로그인하도록 수정하겠습니다.
