### ISSUE TITLE
[bug] 리뷰 답글 삭제 관련

### ISSUE THREAD

**Issue by lazzzykim** [JYOH3246/BackOffice#33]
리뷰 댓글 delete가 swagger에선 204로 정상적으로 표시가 되었는데,

db에선 삭제가 되지 않는 에러가 발생했습니다.

원인을 찾아본 결과 Review Entity와 ReplyByReview Entity의 연관관계 설정에 오류가 있었습니다.

리뷰를 삭제하면 고아객체도 같이 삭제되게 하기위해 CascadeType을 ALL로 설정했는데, 이렇게 되었을 때

답글은 부모인 리뷰의 생명주기를 따라가다보니 답글만 삭제가 되지 않는 상태가 된 것입니다.

그래서 Cascade설정을 삭제 후 orphanRemoval = true를 사용하니 답글도 독자적으로 삭제를 할 수 있고,

리뷰가 삭제되면 리뷰의 답글도 같이 삭제가 되는것을 확인했습니다.

강의자료에선 Cascade와 orphanremoval이 항상 같이 붙어있어서 반드시 같이 사용해야 하는것으로 이해를 했었는데,

cascade와 orphanremoval은 따로따로 사용할 수 있다는 것을 알게되었습니다. 참고하시면 좋을 것 같아 이슈 올립니다.

그리고 현재 기능은 잘 작동하나 자꾸 ReplyId 관련 ModelNotFoundException이 발생합니다..
익셉션이 자꾸 id:1 만 찾아서 발생하는데 실제로 db에 작성되는
id는 1씩 올라가는 형태입니다. 
GeneratedValue 어노테이션을 빼야할까요?

**Comment by JYOH3246** [comment]
코드를 봐야 말씀드릴 수 있을 것 같습니다.

**Comment by lovelyunsh** [comment]
>그리고 현재 기능은 잘 작동하나 자꾸 ReplyId 관련 ModelNotFoundException이 발생합니다..
>익셉션이 자꾸 id:1 만 찾아서 발생하는데 실제로 db에 작성되는
>id는 1씩 올라가는 형태입니다.

현재 실행 했을 때는 문제가 있어 보이지 않습니다. 좀 더 자세히 설명 가능하실까요?

**Comment by lazzzykim** [comment]
storeId, reviewId, replyId 값 입력 후 테스트 해보니 404 
{
  "message": "Model reply not found with given id: 1"
}
이 나옵니다..

그 후에 db에서 reply id값을 1로 수정해서 다시 Execute 하면 또 수정은 되구요..

대댓글을 작성 할 수록 db에 reply Id값은 증가하는데 익셉션은 자꾸 1만 찾아서 발생하는것 같습니다
