### ISSUE TITLE
[기능] 주문 기능 순서도

### ISSUE THREAD

**Issue by lovelyunsh** [JYOH3246/BackOffice#5]
![image](https://github.com/JYOH3246/BackOffice/assets/43734328/7d52e91b-47ee-4ad4-889f-8d5ef37d77e7)

주문 프로세스가 복잡하다 보니 프로세스를 순서도로 나타냈습니다.

여기서 빠진 부분이나 이상한 부분 있는지 한번 확인해 주시기 바랍니다.

**Comment by JYOH3246** [comment]
특이사항은 없는 듯 합니다.
위 프로세스대로 개발을 진행해 보되, 테스트 시에 기획적으로 이상한 점이 생기면 그때 프로세스를 다시 점검해 봐야할 듯합니다.

**Comment by lovelyunsh** [comment]
네 다시 보니 주문 취소 시 금액 환불 하는 프로세스도 필요할 것 같습니다.
해당 부분까지 추가하고 pdf로 slack에 올려두겠습니다.

**Comment by lovelyunsh** [comment]
[주문 프로세스.pdf](https://github.com/JYOH3246/BackOffice/files/14019841/default.pdf)

**Comment by lazzzykim** [comment]
궁금한점이 있습니다.
주문 승인/거절, 환불 같은 기능도 백오피스 부분이라고 봐도 되는걸까요?

**Comment by lovelyunsh** [comment]
> 궁금한점이 있습니다. 주문 승인/거절, 환불 같은 기능도 백오피스 부분이라고 봐도 되는걸까요?

백오피스는 admin 페이지의 느낌이라 전체적인 데이터를 관리하는 역할인 것 같고,
승인/거절, 환불 같은 기능은 가게 주인이라는 actor가 가지는 역할이라고 볼 수 있을 것 같아요!
