### ISSUE TITLE
[API 명세서] 일반 사용자 / 계좌 / 계좌 입금

### ISSUE THREAD

**Issue by JYOH3246** [JYOH3246/BackOffice#9]
현재 문서 상에는 계좌에 입금을 했을 때는 Response가 존재하지 않습니다.
편의성을 고려하면, 입금을 완료했을 때 입금된 금액을 Response로 보여주는 것이 좋을 것 같습니다.

**Comment by lovelyunsh** [comment]
말씀하신 방법이 좋은 것 같습니다. 수정하겠습니다.

https://docs.google.com/spreadsheets/d/1IBSx4MNMpBJp5ZjguWEJdB4CDQiS_cr2QuPW_KS_C_g/edit#gid=0
